version: '3.8'

services:
  backend:
    container_name: nest-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - ollama
    command: npm run start:dev # enable hot reloading

  ollama:
    container_name: ollama-ai
    image: ollama/ollama
    ports:
      - '11434:11434'
    restart: always
    volumes:
      - ollama-data:/root/.ollama

volumes:
  ollama-data:
